# This work is licensed under the terms of the GNU GPL, version 2.  See
# the COPYING file in the top-level directory.
#

language: c

compiler:
  - gcc

sudo: required
dist: trusty

# Remove bogus python installations from PATH,
# see https://github.com/travis-ci/travis-ci/issues/5326
before_install:
  - export PATH=$(echo $PATH | sed 's/\/opt\/python[^:]*//g')

install:
  # Install additional packages
  - sudo apt-add-repository 'deb http://archive.ubuntu.com/ubuntu xenial main'
  - sudo apt-get update -qq 
  - sudo apt-get install -qq python-mako make
  - if [ ! -L ci/xenomai ]; then
        pushd ci;
        git clone --depth=50 --branch=v3.0.7 https://github.com/jlauenstein/xenomai.git xenomai;
        popd;
    fi

cache:
  directories:
  - ci/xenomai

script:
  - mv .config cfg.xeno; make x86_64_defconfig; alias
  - grep CONFIG_IPIPE .config
  - cp .config cfg.ipipe; grep -v CONFIG_IPIPE >.config
  - echo "===== NoIpipe/x86 build ====="
  - make -j `nproc` bzImage modules; ls -l .config vmlinux
  - make clean; mv cfg.ipipe .config
  - echo "===== Ipipe/x86 build ====="
  - make -j `nproc` bzImage modules; ls -l .config vmlinux
  - make clean; mv cfg.xeno .config
  - ci/xenomai/scripts/prepare-kernel.sh --arch=x86 --verbose
  - git status -v
  - git status -v ci/xenomai/
  - ls -la .config include/ ci/*; echo "===== Cobalt/x86 build ====="
  - make -j `nproc` bzImage modules
  - pushd ci/xenomai; ./scripts/bootstrap; popd
  - mkdir xenobuild; pushd xenobuild
  - ../ci/xenomai/configure --with-core=cobalt --enable-smp --enable-pshared
  - make -j `nproc` all
  - popd
  - ls -la . xenobuild

#  - if [ ${COVERITY_SCAN_BRANCH} != 1 ];
#        then ci/build-all-configs.sh;
#    fi
