# This work is licensed under the terms of the GNU GPL, version 2.  See
# the COPYING file in the top-level directory.
#

env:
  matrix:
    - TARGET=x86
    - TARGET=i386
    - TARGET=arm

language: c

compiler:
  - gcc

sudo: required
dist: trusty

# Remove bogus python installations from PATH,
# see https://github.com/travis-ci/travis-ci/issues/5326
before_install:
  - export PATH=$(echo $PATH | sed 's/\/opt\/python[^:]*//g')

install:
  # Install additional packages
  - sudo apt-add-repository 'deb http://archive.ubuntu.com/ubuntu xenial main'
  - sudo apt-get update -qq 
  - sudo apt-get install -qq make
  - if [ ! -d ci/xenomai ]; then
        pushd ci;
        git clone --depth=50 --branch=v3.0.7 https://github.com/jlauenstein/xenomai.git xenomai;
        popd;
    fi

cache:
  directories:
  - ci/xenomai

script:
  - ci/build_all.sh
